const projects = [
    {
        name: "Learning Management System",
        image: "./assets/project-1.0.png",
        languages: "HTML, CSS, PHP, MySQL",
        description: "Learning Management System is a responsive e-commerce website built using HTML, CSS, and JavaScript. The application offers a user-friendly interface for browsing products, adding items to the cart, and completing purchases. Key features include a dynamic product catalog, real-time inventory updates, and a secure checkout process.",
        github: "https://github.com/Scripts-By-Hamza/LMS-Project",
        live: "",
    },
    {
        name: "Apex Bazar E-Commerce Website",
        image: "./assets/project-3.0.png",
        languages: "HTML, CSS, JavaScript",
        description: "Apex Bazar E-Commerce Website is a responsive e-commerce website built using HTML, CSS, and JavaScript. The application offers a user-friendly interface for browsing products, adding items to the cart, and completing purchases. Key features include a dynamic product catalog, real-time inventory updates, and a secure checkout process.",
        github: "https://github.com/Scripts-By-Hamza/Apex-bazzar-E-Commerce",
        live: "",
    },
    {
        name: "Bubble Game JavaScript",
        image: "./assets/project-2.0.png",
        languages: "HTML, CSS, JavaScript",
        description: "Bubble Project is an interactive web-based game developed using HTML, CSS, and JavaScript. The application challenges players to achieve a target score by selecting the correct bubbles within a limited time frame. Key features include a dynamic scoring system, a countdown timer, and real-time game feedback.",
        github: "https://github.com/Scripts-By-Hamza/Bubble-Project",
        live: "https://scripts-by-hamza.github.io/Bubble-Project/",
    },
    {
        name: "Blog Post Project",
        image: "./assets/project-4.0.png",
        languages: "HTML, CSS, JavaScript",
        description: "A refined, typography-driven blogging platform highlighting diverse stories—designed for clarity, structure, and reading enjoyment.",
        github: "https://github.com/Scripts-By-Hamza/Blog-Post-Website",
        live: "https://scripts-by-hamza.github.io/Blog-Post-Website/",
    },
    {
        name: "Tool Grid Project",
        image: "./assets/project-5.0.png",
        languages: "HTML, CSS, JavaScript",
        description: "ToolGrid is a sleek, web-based toolkit directory built with HTML, CSS, and JavaScript, hosted via GitHub Pages. Designed as a centralized hub for developers, it showcases 42 top development tools across 9 thoughtfully curated categories—including Coding Tools, Image Generation, Frontend, Backend, Mobile Dev, Game Dev, Data Visualization, Design Tools, and a section for Free Resources.",
        github: "https://github.com/Scripts-By-Hamza/ToolGrid",
        live: "https://scripts-by-hamza.github.io/ToolGrid/",
    },
    {
        name: "Food Restaurants",
        image: "./assets/project-6.0.png",
        languages: "HTML, CSS, JavaScript",
        description: "Mom’s Kitchen is a modern, client-facing restaurant web application built using HTML, CSS, and JavaScript, and deployed via GitHub Pages. The homepage features a streamlined navigation menu (Home, Menu, Contact Us, Reserve Table).",
        github: "https://github.com/Scripts-By-Hamza/Food-Restaurants-Website",
        live: "https://scripts-by-hamza.github.io/Food-Restaurants-Website/",
    },
     {
        name: "SoulFly Travel Agency",
        image: "./assets/project-7.0.png",
        languages: "HTML, CSS, JavaScript",
        description: "SoulFly Travel Agency is a modern, client-facing travel agency web application built using HTML, CSS, and JavaScript, and deployed via GitHub Pages. The homepage features a streamlined navigation menu (Home, About Us, Services, Contact Us).",
        github: "https://github.com/Scripts-By-Hamza/SoulFly-vanilla'",
        live: "https://scripts-by-hamza.github.io/SoulFly-vanilla/",
    },
]